# Use Redis cache server
#    FROM postgres
#    LABEL authors="jonghechoi"
#
#    ENV POSTGRES_PASSWORD "1234"
#
#    CMD ["docker-entrypoint.sh", "postgres"]

FROM redis:7.0-alpine

LABEL maintainer "sosinnmi2 <sosinnmi@naver.com>"